language: python
python:
    - '3.8'

install:
    - pip install -r requirements-dev.txt

env:
    - DEMO_HOME="$HOME/build/ampahwa"

script:
    - make tests

# deploy to heroku on push to master
deploy:
    - provider: heroku
      api_key: aed185bc-451b-40bf-91bc-74505f2fae7c
      app: gumbodama
      on:
          branch: master
